"""Time-dependent routing (TDVRPTW / TDVRP) contract and canonical checker.

See the TD benchmark standard in the MAMUT-routing repository for the format
specification: instance ``.vrp.json`` files reference an ATF sidecar
(``.atf.json`` / ``.atf.json.gz``) holding one arrival-time NDCPWLF per arc.
"""

from mamut_routing_lib.td.artifacts import (
    ATF_GZIP_SUFFIX,
    ATF_PLAIN_SUFFIX,
    ATFFormatError,
    InstanceATFs,
    LoadedTDInstance,
    atfs_to_canonical_json_bytes,
    compute_atf_sha256,
    get_atf_path_for_instance,
    load_instance_atfs,
    load_td_benchmark_instance,
    load_td_instance,
    save_instance_atfs,
    td_instance_from_payload,
)
from mamut_routing_lib.td.bks import (
    annotate_td_bks_optimality,
    create_td_bks_from_solution,
    save_td_solution_as_bks_if_improved,
)
from mamut_routing_lib.td.igp import (
    IGP_GZIP_SUFFIX,
    IGP_MATERIALIZER_GENERATOR,
    IGP_PLAIN_SUFFIX,
    IGPFormatError,
    InstanceCategories,
    build_arc_atf,
    categories_to_canonical_json_bytes,
    compute_categories_sha256,
    euclidean_distance,
    ichoua_travel_time,
    load_instance_categories,
    materialize_instance_atfs,
    save_instance_categories,
)
from mamut_routing_lib.td.checker import (
    TDRouteEvaluation,
    TDSolutionCheckResult,
    canonical_route_order,
    check_td_solution,
    compute_route_duration,
    compute_route_ready_time_function,
    compute_solution_cost,
)
from mamut_routing_lib.td.models import (
    ATF_FORMAT,
    ATF_FORMAT_VERSION,
    IGP_CATEGORIES_FORMAT,
    IGP_CATEGORIES_FORMAT_VERSION,
    TD_ATF_MODEL,
    TD_IGP_MODEL,
    AnyTDBenchmarkInstance,
    BenchmarkInstanceTDVRP,
    BenchmarkInstanceTDVRPTW,
    TDArrivalFunctionsRef,
    TDIGPProfileRef,
)
from mamut_routing_lib.td.pwlf import NDCPWLF, PWLFError, make_theta

__all__ = [
    "ATF_FORMAT",
    "ATF_FORMAT_VERSION",
    "ATF_GZIP_SUFFIX",
    "ATF_PLAIN_SUFFIX",
    "ATFFormatError",
    "AnyTDBenchmarkInstance",
    "BenchmarkInstanceTDVRP",
    "BenchmarkInstanceTDVRPTW",
    "IGPFormatError",
    "IGP_CATEGORIES_FORMAT",
    "IGP_CATEGORIES_FORMAT_VERSION",
    "IGP_GZIP_SUFFIX",
    "IGP_MATERIALIZER_GENERATOR",
    "IGP_PLAIN_SUFFIX",
    "InstanceATFs",
    "InstanceCategories",
    "LoadedTDInstance",
    "NDCPWLF",
    "PWLFError",
    "TDArrivalFunctionsRef",
    "TDIGPProfileRef",
    "TDRouteEvaluation",
    "TDSolutionCheckResult",
    "TD_ATF_MODEL",
    "TD_IGP_MODEL",
    "annotate_td_bks_optimality",
    "atfs_to_canonical_json_bytes",
    "build_arc_atf",
    "canonical_route_order",
    "categories_to_canonical_json_bytes",
    "check_td_solution",
    "compute_atf_sha256",
    "compute_categories_sha256",
    "compute_route_duration",
    "compute_route_ready_time_function",
    "compute_solution_cost",
    "create_td_bks_from_solution",
    "euclidean_distance",
    "get_atf_path_for_instance",
    "ichoua_travel_time",
    "load_instance_atfs",
    "load_instance_categories",
    "load_td_benchmark_instance",
    "load_td_instance",
    "make_theta",
    "materialize_instance_atfs",
    "save_instance_atfs",
    "save_instance_categories",
    "save_td_solution_as_bks_if_improved",
    "td_instance_from_payload",
]
